### ISSUE TITLE
Fix codecov unknown and CI failing in badge

### ISSUE THREAD

**Issue by Filippo1598** [diffpy/diffpy.fourigui#20] opened 2024-10-07 15:36 UTC
![image](https://github.com/user-attachments/assets/7351fd31-f096-4846-b84d-78760b84c704)

**Comment by bobleesj** [comment] 2024-10-07 19:18
CI: https://github.com/diffpy/diffpy.fourigui/actions/runs/11182735518/job/31089685986

The CI is trying to upload to codecov as intended: 

```
Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

I think the codecov token is not found in the repository? @sbillinge let's do this on Thu

**Comment by bobleesj** [comment] 2024-10-10 14:49
not closed

**Comment by bobleesj** [comment] 2024-10-24 10:53
<img width="555" alt="Screenshot 2024-10-24 at 6 53 10 AM" src="https://github.com/user-attachments/assets/d781d57f-bc84-49c8-a2ae-722fb741af46">

Closed by https://github.com/diffpy/diffpy.fourigui/pull/34

@sbillinge Thanks!

**Comment by bobleesj** [comment] 2024-10-24 10:53
@Filippo1598 Could you please close this issue?

**Closed** 2024-10-24 20:12 UTC
